script:
#   - "wget -qO- https://raw.github.com/8iq/wflow/bootstrap.sh | sudo bash"
  - "chmod +x bootstrap.sh"
  - "sudo ./bootstrap.sh"
  - "/var/lib/wflow/venv/bin/activate && python packages/wshell/test"
