language: python
python:
  - "3.4"
  - "2.7"

script:
#   - "wget -qO- https://raw.github.com/8iq/wflow/bootstrap.sh | sudo bash"
  - "chmod +x bootstrap.sh"
  - "sudo ./bootstrap.sh"
  - "sudo make test"
  - "sudo make full_clean"
  - "sudo make install"
  - "sudo make test"
  - "make count"
