#!/usr/bin/env python3
# coding=utf-8
from __future__ import unicode_literals, print_function, absolute_import, \
    generators, with_statement, nested_scopes, division
import sys

from wshell.core import Core
from wshell.manager import Manager
from wutil.env import load_env_for_file

__author__ = 'pahaz'
__version__ = '0.2.1'


def puts(s):
    sys.stderr.write(s)


class WflowCore(Core):
    def initialize(self, argv):
        puts(self.copyright)
        super(WflowCore, self).initialize(argv)


def main(argv):
    description = "Heroku like deploy tools."
    copyright = '\nHi! I am `wflow` v {0} \n2014 (c) {1}\n\n' \
        .format(__version__, __author__)

    env = load_env_for_file(__file__)

    directory_for_storing_plugins = env.SCRIPT_PLUGIN_PATH
    directory_for_storing_data = env.SCRIPT_DATA_PATH
    directory_for_storing_venv = env.SCRIPT_VENV_PATH
    owner_username = env.SCRIPT_USER_NAME

    cm = Manager(directory_for_storing_plugins,
                 directory_for_storing_venv,
                 env)
    app = WflowCore(cm,
                    copyright=copyright,
                    description=description,
                    version=__version__)
    return app.run(argv)


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
