#!/usr/bin/env python3
# coding=utf-8
from __future__ import unicode_literals, print_function, absolute_import, \
    generators, with_statement, nested_scopes, division
import sys

from wshell.core import Core
from wshell.manager import Manager
from wutil.parser import load_configs

__author__ = 'pahaz'
__version__ = '1.1'


def puts(s):
    sys.stderr.write(s + '\n')


class WflowCore(Core):
    def initialize_app(self, argv):
        puts(self.copyright)


def main(argv):
    description = "Heroku like deploy tools."
    copyright = '\nHi! I am `wflow` v {0} \n2014 (c) {1}\n\n' \
        .format(__version__, __author__)

    options = load_configs(__file__)

    directory_for_storing_plugins = options.SCRIPT_PLUGIN_PATH
    directory_for_storing_data = options.SCRIPT_DATA_PATH
    directory_for_storing_venv = options.SCRIPT_VENV_PATH
    owner_username = options.SCRIPT_USER_NAME

    cm = Manager(directory_for_storing_plugins)
    app = WflowCore(cm,
                    copyright=copyright,
                    description=description,
                    version=__version__)
    return app.run(argv)


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
