#!/usr/bin/env python3
import os

__author__ = 'pahaz'
__plugin_root__ = os.path.join(os.path.dirname(__file__), '..')


if __name__ == "__main__":
    # cd to plugin root
    os.chdir(__plugin_root__)

    NAME = os.environ.get('PLATFORM_NAME')
    PLUGIN_INSTALLER_COMMAND = os.environ.get('PLATFORM_PLUGIN_INSTALLER_COMMAND')
    TRIGGER_EVENT_COMMAND = os.environ.get('PLATFORM_TRIGGER_EVENT_COMMAND')
    USER_NAME = os.environ.get('PLATFORM_USERNAME')
    DATA_PATH = os.environ.get('PLATFORM_DATA_PATH')
    PLUGINS_PATH = os.environ.get('PLATFORM_PLUGINS_PATH')
    VENV_PATH = os.environ.get('PLATFORM_VENV_PATH')

    print("event example-python3 ... ")
    print("event example-python3 ... ")
    print(os.system("printenv"))
    print('EVENT!',
          NAME, PLUGIN_INSTALLER_COMMAND, TRIGGER_EVENT_COMMAND, USER_NAME,
          DATA_PATH, PLUGINS_PATH, VENV_PATH)
    print('hook ... example ...')
    print('hook ... example ...')
