#!/usr/bin/env bash
set -eo pipefail; [[ $TRACE ]] && set -x

# cd to plugin root
PLUGIN_ROOT=`dirname $0`/../
cd $PLUGIN_ROOT

echo "event example-bash ... "
echo "event example-bash ... "
printenv
echo ...
echo PLATFORM_NAME=$PLATFORM_NAME
echo PLATFORM_PLUGIN_INSTALLER_COMMAND=$PLATFORM_PLUGIN_INSTALLER_COMMAND
echo PLATFORM_TRIGGER_EVENT_COMMAND=$PLATFORM_TRIGGER_EVENT_COMMAND
echo PLATFORM_USERNAME=$PLATFORM_USERNAME
echo PLATFORM_DATA_PATH=$PLATFORM_DATA_PATH
echo PLATFORM_PLUGINS_PATH=$PLATFORM_PLUGINS_PATH
echo hook ... example ...
echo hook ... example ...
