#!/usr/bin/env python3
import os

__author__ = 'pahaz'
__plugin_root__ = os.path.join(os.path.dirname(__file__), '..')


if __name__ == "__main__":
    # cd to plugin root
    os.chdir(__plugin_root__)

    NAME = os.environ.get('SCRIPT_NAME')
    PLUGIN_INSTALLER_NAME = os.environ.get('SCRIPT_PLUGIN_INSTALLER_NAME')
    TRIGGER_EVENT_NAME = os.environ.get('SCRIPT_TRIGGER_EVENT_NAME')
    USER_NAME = os.environ.get('SCRIPT_USER_NAME')
    DATA_PATH = os.environ.get('SCRIPT_DATA_PATH')
    PLUGINS_PATH = os.environ.get('SCRIPT_PLUGINS_PATH')
    VENV_PATH = os.environ.get('SCRIPT_VENV_PATH')

    print("event example-python3 ... ")
    print("event example-python3 ... ")
    print(os.system("printenv"))
    print('EVENT!',
          NAME, PLUGIN_INSTALLER_NAME, TRIGGER_EVENT_NAME, USER_NAME,
          DATA_PATH, PLUGINS_PATH, VENV_PATH)
    print('hook ... example ...')
    print('hook ... example ...')
